language: go
sudo: required

go_import_path: distroless_sh_bug

services:
  - docker

cache:
  directories:
    - $HOME/bazel/install

before_install:
  - sudo apt-get install -y --no-install-recommends wget
  - cd ${HOME}/bazel/install
  - wget --no-clobber https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel_0.5.4-linux-x86_64.deb
  - sha256sum -c ${HOME}/gopath/src/distroless_sh_bug/bazel_0.5.4-linux-x86_64.deb.sha256
  - sudo apt-get purge openjdk-9*
  - sudo apt-get purge oracle-java9-installer
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update && sudo apt-get install -y oracle-java8-installer
  - sudo dpkg -i bazel_0.5.4-linux-x86_64.deb
  - cd -

install:
  - echo nope

script:
  - bazel --output_groups=race run //hello:prod
  - docker run -it --rm bazel/hello:prod
